### ISSUE TITLE
vehicle.capability() returning error

### ISSUE THREAD

**Issue by BillyCroan** [ianjwhite99/sync-connect-sdk#55]
When calling currentVehicle.capability(), I get a python traceback.  I suspect ford discontinued the URI that was providing capability information. What info did it used to have?

**To Reproduce**
print( currentVehicle.capability() )

Traceback (most recent call last):
  File "/home/bcroan/.local/lib/python3.6/site-packages/connectedcar/requester.py", line 35, in call
    raise E.ResourceNotFoundException(response)
  File "/home/bcroan/.local/lib/python3.6/site-packages/connectedcar/exceptions.py", line 9, in __init__
    json = response.json()
  File "/usr/lib/python3.6/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib64/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.6/json/decoder.py", line 342, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 5 (char 4)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/bcroan/bin/LogFusionData.py", line 30, in <module>
    print( currentVehicle.capability() )
  File "/home/bcroan/.local/lib/python3.6/site-packages/connectedcar/vehicle.py", line 137, in capability
    const.USER_URL, 'capability/v1/vehicles/' + self.vehicle_id)
  File "/home/bcroan/.local/lib/python3.6/site-packages/connectedcar/api.py", line 59, in get
    return requester.call('GET', url, headers=headers)
  File "/home/bcroan/.local/lib/python3.6/site-packages/connectedcar/requester.py", line 49, in call
    raise E.SyncException("Unexpected error") from e
connectedcar.exceptions.SyncException: Unexpected error

**Expected behavior**
list capabilities of vehicle

**Desktop (please complete the following information):**
Fedora 36, Python 3

I an able to enumerate vin numbers on the account and door lock status, so authentication is working properly.

**Comment by ianjwhite99** [comment]
Fixed in [v1.3.7](https://github.com/ianjwhite99/connected-car-python-sdk/releases/tag/1.3.7)
